M48
; DRILL file {KiCad (6.0.7-1)-1} date 2022 September 14, Wednesday 08:46:15
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-14T08:46:15+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.400
%
G90
G05
T1
X46.1Y-53.6
X46.1Y-124.4
X211.9Y-53.6
X211.9Y-124.4
X211.9Y-124.4
X211.9Y-124.4
T0
M30
